### ISSUE TITLE
keenio benefits....

### ISSUE THREAD

**Issue by sirvon** [charandas/mixpanel-to-keen#1]
thanks for exposing this script..

Can you eloborate on why getting this data in keen is better ?

**Comment by charandas** [comment]
@sirvon I am building something for a client where the keen custom dashboards might come handy. The query API provided by keen is much more flexible and powerful. You should refer to their docs and maybe make a test account to confirm these observations.

Then again, mixpanel might be perfectly fine for someone else's use case, with its web client, or data API.

**Comment by sirvon** [comment]
thanks for the insight
